#!/bin/bash
#
#   Add package.json files to cjs/mjs subtrees
#   Based on https://github.com/sensedeep/dynamodb-onetable/blob/956211b862995d3d8e6730ab30bb05e2cfcb27e6/fixup
#   See https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html
#

cat >dist/cjs/package.json <<!EOF
{
    "type": "commonjs"
}
!EOF

cat >dist/mjs/package.json <<!EOF
{
    "type": "module"
}
!EOF

cp src/modules.d.ts dist/